# Brewfile, similar to a Gemfile but for Homebrew
# Go to https://github.com/Homebrew/homebrew-bundle for more info

# Taps
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/core"

# Essentials
brew "bat"
brew "fd"
brew "git"
brew "jq"
brew "neovim"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "shellcheck"
brew "thefuck"
brew "tmux"
brew "tree"
brew "zsh"
brew "zsh-syntax-highlighting"

# Ruby
brew "ruby-build"
brew "rbenv"

# Things to build other things
brew "autoconf"
brew "automake"
brew "cmake"
brew "gcc"

# Nice to haves
brew "autopep8"
brew "cowsay"
brew "ctop"
brew "dos2unix"
brew "exa"
brew "findutils"
brew "gist"
brew "gnutls"
brew "gh"
brew "grep"
brew "hadolint"
brew "htop"
brew "hub"
brew "mpssh"
brew "mtr"
brew "ngrep"
brew "nmap"
brew "node"
brew "openssh"
brew "rename"
brew "screenfetch"
brew "speedtest-cli"
brew "spoof-mac"
brew "ssh-copy-id"
brew "stunnel"
brew "tig"
brew "watch"
brew "wget"
brew "xz"
brew "yamllint"

# Casks
#cask "cyberduck"
#cask "docker"
#cask "evernote"
#cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "istat-menus"
cask "karabiner-elements"
#cask "kodi"
#cask "macdown"
#cask "marked"
#cask "nzbget"
cask "slack"
#cask "transmission"
cask "tunnelblick"
#cask "unetbootin"
cask "vagrant"
cask "visual-studio-code"
cask "vlc"
cask "wireshark"

