--- {}
#AllCops:
#  NewCops: enable
#  Exclude:
#    - '**/*.erb'
#
#Style/FrozenStringLiteralComment:
#  Enabled: false
#Style/ClassAndModuleChildren:
#  EnforcedStyle: nested
#Layout/SpaceBeforeComment:
#  Enabled: false
#Metrics/BlockLength:
#  Enabled: false
#Metrics/LineLength:
#  Enabled: false
#Metrics/MethodLength:
#  Enabled: false
#Metrics/PerceivedComplexity:
#  Enabled: false
#Metrics/CyclomaticComplexity:
#  Enabled: false
#Metrics/AbcSize:
#  Enabled: false
