#!/bin/bash

green="$(tput setaf 2)"
red="$(tput setaf 1)"
yellow="$(tput setaf 3)"
nc="$(tput sgr0)"

# Install Vundle
if [[ ! -e ~/.vim/bundle/Vundle.vim ]]; then

    prompt="$(printf "\n%s" "${yellow}Vundle not found. Would you like to install it? y/n: ${nc}")"
    read -ep "$prompt" ans
    case "$ans" in
        y|Y) git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle
             vundle="1"
             vim +PluginInstall +qall
             ;;
        *)  true
            vundle="0"
            ## Add bit in here to link non-vundle .vimrc instead of normal one.
            ;;
    esac

fi


# Setup Vundle plugins
if [[ $vundle == 1 ]]; then
    printf "%s\n" "${yellow}Setting up Vundle plugins"
    vim +PluginInstall +qall
    printf "\n"
fi
