#!/usr/bin/env ruby

require 'json'
require 'open3'
require 'rubygems'
require 'yaml'

# Cross-platform way of finding an executable in the $PATH.
# which('ruby') #=> /usr/bin/ruby
def which(cmd)
  exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
  ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
    exts.each do |ext|
      exe = File.join(path, "#{cmd}#{ext}")
      return exe if File.executable?(exe)
    end
  end
  nil
end

# Takes an array where the first element is the command and the other elements are command flags.
# Returns true on cmd success.
def run(cmd)
  stdout, stderr, status = Open3.capture3(*cmd)

  if status.success?
    puts stdout unless stdout.empty?
    true
  else
    warn(stdout)
    warn(stderr)
    exit 1
  end
end

def tofu_fmt(file)
  if which('tofu')
    run(['tofu', 'fmt', '-check', file])
  else
    puts 'WARNING: tofu not installed. Skipping syntax check of Terraform code.'
  end
end

def tflint(file)
  if which('tflint')
    run(['tflint', '--chdir', File.dirname(file), "--filter=#{File.basename(file)}"])
  else
    puts 'WARNING: tflint not installed. Skipping lint check of Terraform code. https://github.com/terraform-linters/tflint'
  end
end

def bash_check(file)
  if which('bash')
    run(['bash', '-n', file])
  else
    puts 'WARNING: bash not found. Skipping syntax check of shell script'
  end
end

def shell_check(file)
  if which('shellcheck')
    run(['shellcheck', file])
  else
    puts 'WARNING: shellcheck not installed. Skipping check of shell script. https://github.com/koalaman/shellcheck#installing'
  end
end

def yaml_check(file)
  YAML.safe_load_file(file)
rescue StandardError => e
  warn("YAML invalid: #{e}")
  exit 1
end

def yaml_lint(file)
  if which('yamllint') # https://github.com/adrienverge/yamllint
    run(['yamllint', '-f', 'parsable', file])
  else
    puts 'yamllint not installed. Skipping YAML style check.'
  end
end

def json_check(file)
  JSON.parse(IO.read(file))
rescue StandardError => e
  warn("JSON invalid: #{e}")
  exit 1
end

def python_lint(file)
  if which('flake8')
    run(['flake8', '--append-config', "#{ENV['HOME']}/.config/flake8", file])
  else
    puts 'flake8 not installed (pip install flake8). Skipping Python style check.'
  end
end

# Go through list of files, and call an appropriate checker.
Open3.capture2('git diff --cached --name-only --diff-filter=ACM')[0].each_line do |file|
  file.chomp!
  puts "Processing #{file}"
  case file
  when /(\.tf$|\.tfvars$)/
    tflint file
    tofu_fmt file
  when /\.sh$/
    bash_check file
    shell_check file
  when /(\.yaml$|\.yml$|\.eyaml$)/
    yaml_check file
    yaml_lint file
  when /\.json$/
    json_check file
  when /\.py$/
    python_lint file
  end
end
